- name: Create local repo config dir
  file:
    path: '{{ vars["jail_" + jail_name + "_new_path"] }}/usr/local/etc/pkg/repos'
    state: directory

- name: Copy FreeBSD repo config in place
  copy:
    src: FreeBSD.conf
    dest: '{{ vars["jail_" + jail_name + "_new_path"] }}/usr/local/etc/pkg/repos/FreeBSD.conf'

- name: Create resolv.conf for install usage in jail
  copy:
    dest: '{{ vars["jail_" + jail_name + "_new_path"] }}/etc/resolv.conf'
    content: |
      nameserver 127.0.0.1

- name: Mounting devFS into chroot for pkg
  ansible.posix.mount:
    src: devfs
    fstab: /tmp/delete-me-fstab
    path: '{{ vars["jail_" + jail_name + "_new_path"] }}/dev'
    fstype: devfs
    state: mounted

- name: Mounting directories
  command:
    /sbin/mount
    -a -F
    {{ dynamic_jails_path }}/configs/{{ vars["jail_" + jail_name + "_newest_id"] }}/fstab
  args:
    warn: no

- name: Restarting syslog
  service:
    name: syslogd
    state: restarted

- include_tasks:
    file: '{{ ansible_roles_path }}/karolyi.ansible-freebsd-jailhost-tools/tasks/chroot/install_packages.yml'
  when:
    - vars['install_packages']|default('') != ''

- include_tasks:
    file: '{{ ansible_roles_path }}/karolyi.ansible-freebsd-jailhost-tools/tasks/chroot/install_packages.yml'
  when:
    - vars['install_packages']|default('') != ''
    - install_result.failed

- name: Fail when install failed
  fail:
    msg: '{{ install_result.msg }}'
  when:
    - vars['install_packages']|default('') != ''
    - install_result.failed

# vim: sw=2
