- name: Cleaning pkg cache
  command:
    /usr/sbin/pkg
    -c {{ vars["jail_" + jail_name + "_new_path"] }}
    clean -ayq

- name: Unmounting directories
  command:
    /sbin/umount
    -a -F
    {{ dynamic_jails_path }}/configs/{{ vars["jail_" + jail_name + "_newest_id"] }}/fstab
  args:
    warn: no

- name: Unmounting devFS from chroot
  mount:
    path: '{{ vars["jail_" + jail_name + "_new_path"] }}/dev'
    state: unmounted

- name: Create resolv.conf for live usage in jail
  copy:
    dest: '{{ vars["jail_" + jail_name + "_new_path"] }}/etc/resolv.conf'
    content: |
      nameserver {{ vars["jail_" + jail_name + "_new_ip4"] }}

# vim: sw=2
